UNSUPPORTED_TYPE = "UNSUPPORTED_TYPE"
EXCLUDED_BY_PATTERN = "EXCLUDED_BY_PATTERN"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
READ_ERROR = "READ_ERROR"
EMPTY_FILE = "EMPTY_FILE"

KNOWN_SKIP_REASONS = {
    UNSUPPORTED_TYPE: "File type is not allowed by INDEX_FILE_TYPES",
    EXCLUDED_BY_PATTERN: "Path matched INDEX_EXCLUDE_PATTERNS",
    FILE_TOO_LARGE: "File exceeds INDEX_MAX_FILE_SIZE_BYTES",
    READ_ERROR: "Failed to read file content",
    EMPTY_FILE: "File has zero size",
}

